version: '3'
services:
  redis:
    image: 'redis:latest'
    expose: 
      - "6379"
  api:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
